version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - shop-network

volumes:
  mongodb:


networks:
  shop-network:
    driver: bridge
